### ISSUE TITLE
right clicking an empty Rice Roll Royale returns the whole thing, making the rice roll infinite

### ISSUE THREAD

**Issue by Inonedn** [PhantomWing/RusticDelight#29]

**Comment by PhantomWing** [comment]
Wow, completely missed that during testing!
I will release a fix soon!

**Comment by MaxKuz67** [comment]
will it be fixed on version 1.20.1?

**Comment by PhantomWing** [comment]
Yes it will be! Right now I'm quite busy but the update is in the works. I will release when I have the time

**Comment by PhantomWing** [comment]
The fix has been released for Neoforge 1.21 and (Neo)forge 1.20! Fabric versions will follow soon.

**Comment by ryleu** [comment]
any update on those fabric versions? still broken for me on the latest fabric version

**Comment by PhantomWing** [comment]
Hi there! I just released a fix for Fabric as well!

**Comment by ryleu** [comment]
thank you! should be good to close this issue then
